### ISSUE TITLE
Any article to guides to convert models?

### ISSUE THREAD

**Issue by dalisoft** [shaqian/tfjs-yolo-demo#1]
Hi @shaqian 

Thanks for awesome demo and converted models.
I also need convert H5 models to Tensorflow Layers or Graph model, but cannot find good article, can you recommend any guide or if you write article i sure will be a lot of readers.

If can implement custom layers, then will be even better, but it's not critical.

Thanks

**Comment by shaqian** [comment]
Hi @dalisoft,

Are you converting models to tfjs? I find there's an official guide about it. 
https://www.tensorflow.org/js/guide/conversion

Thanks,
Qian

**Comment by dalisoft** [comment]
I tried out from official guide, but unsuccessful, so decided to ask from you. 

Thanks for reply
